Major updates; works on linux & Mac

diff --git a/logsum b/logsum
--- a/logsum
+++ b/logsum
@@ -1,7 +1,8 @@
 #!/usr/bin/env bash
 
 # -----------------------------------------------------------------------------
-#   logsum: An Interactive Command-Line Interface Pilot's Logbook Summary Tool
+#   logsum: An Interactive, Command-Line Interface Pilot's Logbook Summary Tool
+#           for Linux-GNU and DarwinBSD (MacOS) Operating Systems.
 #
 #   Copyright (c) 2017
 #   Author: Woods Wannamaker (woods.wannamaker@gmail.com)
@@ -47,26 +48,41 @@ reg_int='^[0-9]+$'
 reg_int_range='(^[1-9]?$)|(^[^-0A-Za-z][0-9 ]+$)'
 reg_float='^[0-9]+\.[0-9]+$'
 reg_word_date='(D|d)(A|a)(T|t)(E|e)'
-
-# SOURCE: https://redd.it/5gtilb
-reg_date='([0-9]{2}(([02468][048])|([13579][26]))-((02-((0[1-9])|([12][0-9])))|((0[469]|11)-((0[1-9])|([12][0-9])|30))|((0[13578]|1[02])-((0[1-9])|([12][0-9])|3[01]))))|([0-9]{4}-((02-((0[1-9])|(1[0-9])|(2[0-8])))|((0[469]|11)-((0[1-9])|([12][0-9])|30))|((0[13578]|1[02])-((0[1-9])|([12][0-9])|3[01]))))'
+# Allow YYYY-MM-DD dates from 20th century or later. Allow 31 DD per MM (be generous). 
+reg_date='(19[0-9]{2}|2[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|(1|2)[0-9]|3[0-1])'
 
 function format_date () {
-# Retruns the date format requested in $1
+# Retruns the date format requested in $1 for date $2 depending on OSTYPE.
 
-    case "$1" in
-        as_epoch)
-            date -d "$2" +%s
-            ;;
-        as_day)
-            date -d @"$2" +%F
-            ;;
-        as_day_time)
-            date +%F_%T
-            ;;
-        get_year)
-            date -d @"$2" +%Y;;
-    esac
+    if [[ "$OSTYPE" == "linux-gnu" ]]; then
+        case "$1" in
+            as_epoch)
+                date -d "$2" +%s
+                ;;
+            as_day)
+                date -d @"$2" +%F
+                ;;
+            as_day_time)
+                date +%F_%H%M%S
+                ;;
+            get_year)
+                date -d @"$2" +%Y;;
+        esac
+    elif [[ "$OSTYPE" == "darwin"* ]]; then
+        case "$1" in
+            as_epoch)
+                date -jf "%F %T" "$2" +%s
+                ;;   
+            as_day)
+                date -r "$2" +%F
+                ;;
+            as_day_time)
+                date +%F_%H%M%S
+                ;;
+            get_year)
+                date -r "$2" +%Y;;
+        esac
+    fi
     
 return 0
 }
@@ -74,7 +90,7 @@ return 0
 function get_field_list () {
 # Returns values for target_field in $1.
 
-    awk -F, -v target_field="${1}" 'FNR>1 {print $target_field }' "$EPOCH_LOG"
+    awk -F, -v target_field="$1" 'FNR>1 {print $target_field }' "$EPOCH_LOG"
     
 return 0
 }
@@ -103,12 +119,22 @@ function epoch_engine () {
 
     printf "%s\n" "Creating the search database..."
     head -1 "$LOGBOOK_FILE" > "$EPOCH_LOG"
-    # SOURCE: http://stackoverflow.com/questions/7965658/
-    TZ=$(date +%Z) awk -F, '/19..|2.../{ OFS = FS;
-    command="date -d" $1 " +%s";
-    command | getline $1;
-    close(command);
-    print }' "$LOGBOOK_FILE" >> "$EPOCH_LOG"
+    TZ=$(date +%Z)
+    
+    # modification of: http://stackoverflow.com/questions/7965658/
+    if [[ "$OSTYPE" == "linux-gnu" ]]; then
+        awk -F, '/19..|2.../{ OFS = FS;
+        command="date -d" $1 " +%s";
+        command | getline $1;
+        close(command);
+        print }' "$LOGBOOK_FILE" >> "$EPOCH_LOG"
+    elif [[ "$OSTYPE" == "darwin"* ]]; then
+        awk -F, '/19..|2.../{ OFS = FS;
+        command="date -jf  %F "$1 "  +%s";
+        command | getline $1;
+        close(command);
+        print }' "$LOGBOOK_FILE" >> "$EPOCH_LOG"
+    fi
 
     _EPOCH_NOW=$(date +%s)
 
@@ -124,6 +150,38 @@ function epoch_engine () {
 return 0
 }       
 
+function is_date_valid () {
+# Returns 0 for valid date; 1 for invalid.
+# Modification of: http://stackoverflow.com/questions/10759162/
+
+    if [[ "$OSTYPE" == "linux-gnu" ]]; then
+        date -d "$1" &> /dev/null; echo $?
+    elif [[ "$OSTYPE" == "darwin"* ]]; then
+        osx_test=$(date -v+1M -v-1M -jf "%F %T" "$1 00:00:00" +"%F %T" 2> /dev/null)
+        if [[ "$osx_test" == "$1 00:00:00" ]]; then
+            echo 0
+        else
+            echo 1
+        fi
+    fi
+}
+
+function is_year_leap () {
+# Returns False if common year; True if leap year.
+# Modification of: http://stackoverflow.com/questions/3220163/
+    year="$1"
+    # modular division method:
+    if [[ $((year % 4)) == 0 && $((year % 100)) != 0 ||  $((year % 400)) == 0 ]]; then
+    # bitwise-AND method:
+#     if [[ $((year & 3)) == 0 && $((year % 25)) != 0 || $((year & 15)) == 0 ]]; then
+        leap=True
+    else
+        leap=False
+    fi
+    echo "$leap"
+return 0
+}
+
 function leap_test () {
 # Determines the number of leap days in a RECENT_RANGES epoch and corrects epoch accordingly.
 # Returns an epoch unchanged or corrected for the number of leaps in the range.
@@ -134,7 +192,8 @@ function leap_test () {
     
     leaps=0
     for (( test_year="$year_epoch_now"; test_year>="$year_test_epoch"; test_year-- )); do
-        if [[  "$test_year-02-29" =~ $reg_date ]]; then
+        if [[ $(is_year_leap "$test_year") == "True" ]]; then   
+  
             test_year_leap_day_epoch=$(format_date as_epoch "$test_year-02-29 00:00:00")
             
             if [[ "$_EPOCH_NOW" -ge "$test_year_leap_day_epoch" && "$test_epoch" -le "$test_year_leap_day_epoch" ]]; then
@@ -172,7 +231,7 @@ return 0
 function category_summary () {
 # Prints a summary table of experience by category. Also builds search_field_index_list
 # and fields_list that are used later. Uses field_type_test function to determine if field
-# type is text,integer, or float. Date field (an integer) is excluded by using reg_word_date.
+# type is text, integer, or float. Date field (an integer) is excluded by using reg_word_date.
 
     fields_list=()
     text_field_index_list=()
@@ -300,7 +359,7 @@ function flight_experience_summary () {
     printf "%-45s %-45s\n\n" "Thru: $epoch_now_date" "Thru: $max_recent_experience_date"     
     printf "%-22s %-9s" "Category" "Totals"
     
-    # This loop prints RECENT_RANGES values with spacing followed by label.
+    # this loop prints RECENT_RANGES values with spacing followed by label.
     for i in "${!RECENT_RANGES[@]}"; do
         printf "   %s " "${RECENT_RANGES[$i]}"
     done
@@ -311,7 +370,7 @@ function flight_experience_summary () {
         field_name="${fields_list[index-1]}"
         field_sum=$(get_epoch_range_sum "$_EPOCH_NOW" "$log_start_epoch" "$index")
  
-        # Determine bounds & the recent_experience value then add to recent_exp_list.
+        # determine bounds & the recent_experience value then add to recent_exp_list
         for search_epoch in "${EPOCH_LIST[@]}"; do
             if [[ "$search_epoch" -gt "$log_end_epoch" || "$_EPOCH_NOW" -lt "$log_start_epoch" ]]; then            
                 value=0
@@ -322,14 +381,14 @@ function flight_experience_summary () {
             recent_exp_list+=( "$value"  )                                    
         done
 
-        # Conditional to print using either integers or float format.       
+        # conditional to print using either integers or float format       
         if [[ "$field_sum" =~ $reg_int ]]; then
             printf "%-22s %6s| " "${field_name} " "$field_sum"  
         elif [[ "$field_sum" =~ $reg_float ]]; then
             printf "%-22s %6.1f| " "${field_name} " "$field_sum"
         fi    
                       
-        # This loop prints recent_exp_list in correct format.       
+        # this loop prints recent_exp_list in correct format.       
         for i in "${!recent_exp_list[@]}"; do
             if [[ $i -eq ${#recent_exp_list[@]}-1 ]]; then
                 printf " %7s\n" "${recent_exp_list[$i]}"
@@ -362,11 +421,11 @@ function aircraft_type_summary () {
         ac_type_id_list=( $(awk -F, -v val="${aircraft_type}" '{ if ($2==val) {print $3} }' "$EPOCH_LOG" | list_sorter) )
         time_in_type=$(awk -F, -v val="${aircraft_type}" -v fld="6" '{ if ($2==val) {s+=$fld} } END {print s}' "$EPOCH_LOG")
 
-        # If duration/time (field 6) is 0, check if simulator (field 13).      
+        # if duration/time (field 6) is 0, check if simulator (field 13)      
         if [ "$time_in_type" = 0 ]; then
             time_in_type=$(awk -F, -v val="${aircraft_type}" -v fld="13" '{ if ($2==val) {s+=$fld} } END {print s}' "$EPOCH_LOG")
         fi
-        # Print ac_type_id_list: wrap if number elements >5; if <5 print on same line
+        # print ac_type_id_list: wrap if number elements >5; if <5 print on same line
         if [[ "${#ac_type_id_list[@]}" -gt 5 ]] ; then
             printf " %-20s %-45s %6.1f\n" "${aircraft_type}" "${ac_type_id_list[*]:0:5}"  "$time_in_type"
             
@@ -440,7 +499,6 @@ function experience_by_year () {
     a="$(format_date get_year "$log_start_epoch")"
     z="$(format_date get_year "$log_end_epoch")"
     
-    # Loop because brace expansion with variables fails in bash.
     years=( )
     for (( i=a; i<=z; i++ )); do  
         years+=("$i")
@@ -482,15 +540,21 @@ function change_date () {
         "l") _EPOCH_NOW="$log_end_epoch"
             printf "%s\n\n" "New Search Start Date: $log_end_date"
             break      
-            ;;           
+            ;;
+            # validate YYYY-MM-DD format vs reg_date then test if date is valid
         *)  if [[ "$new_date" =~ $reg_date ]]; then
-                _EPOCH_NOW=$(format_date as_epoch "$new_date")
-                printf "%s\n\n" "New Search Start Date: $new_date"
-                break
+                is_valid=$(is_date_valid "$new_date")
+                if [[ "$is_valid" -eq 0 ]]; then
+                    _EPOCH_NOW=$(format_date as_epoch "$new_date 00:00:00")
+                    printf "%s\n\n" "New Search Start Date: $new_date"
+                    break
+                else
+                    printf "%s\n\n" "Invalid date or format!"
+                fi
             else
                 printf "%s\n\n" "Invalid date or format!"
             fi
-            ;;              
+            ;;
         esac
     done
     build_epoch_list
@@ -512,7 +576,7 @@ function sort_custom_ranges () {
         min="${min_max[0]}"
         sorted_list+=( "$min" )
         
-        # remove min from copy_list by making tmp_list excluding min; make copy==new and reset min.       
+        # remove min from copy_list by making tmp_list excluding min; make copy==new and reset min      
         tmp_list=()
         for val in "${copy_list[@]}"; do
             if [ "$val" != "$min" ]; then
@@ -707,7 +771,8 @@ startup_notice
 menu_item_list=( 1 2 3 4 5 6 d )
 while true; do
     read -r -p "Enter Selection: " opt
-    if ( echo "${menu_item_list[@]}" | grep -Eq "$opt" ); then
+    # modification of: http://stackoverflow.com/questions/8063228/
+    if [[ ${menu_item_list[@]} =~ (^|[[:space:]])$opt($|[[:space:]]) ]]; then
         rm -f $OUTPUT_FILE
     fi        
     case $opt in
